// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAMsNeUuRT-_S-KMkSFzZl52oh_WHSSm1c",
    authDomain: "pindap-app.firebaseapp.com",
    projectId: "pindap-app",
    storageBucket: "pindap-app.appspot.com",
    messagingSenderId: "444762270326",
    appId: "1:444762270326:android:e2a2feab754019cbf74d57",
    measurementId: "G-LGH3CV6S6P",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMsNeUuRT-_S-KMkSFzZl52oh_WHSSm1c',
    appId: '1:444762270326:android:e2a2feab754019cbf74d57',
    messagingSenderId: '444762270326',
    projectId: 'pindap-app',
    storageBucket: "pindap-app.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMsNeUuRT-_S-KMkSFzZl52oh_WHSSm1c',
    appId: '1:444762270326:android:e2a2feab754019cbf74d57',
    messagingSenderId: '444762270326',
    projectId: 'pindap-app',
    storageBucket: 'pindap-app.appspot.com',
    iosClientId:
        '929684808307-6sldlr38ma73q98ks141n79u81re2m8a.apps.googleusercontent.com',
    iosBundleId: 'com.daffa.pindap_todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMsNeUuRT-_S-KMkSFzZl52oh_WHSSm1c',
    appId: '1:444762270326:android:e2a2feab754019cbf74d57',
    messagingSenderId: '444762270326',
    projectId: 'pindap-app',
    storageBucket: 'pindap-app.appspot.com',
    iosClientId:
        '929684808307-6sldlr38ma73q98ks141n79u81re2m8a.apps.googleusercontent.com',
    iosBundleId: 'com.daffa.pindap_todolist',
  );
}
